export const mockUser = {
  id: "user-1",
  name: "Jane Doe",
  email: "demo@devstash.io",
  image: null,
  isPro: true,
  plan: "Pro Plan",
  createdAt: new Date("2026-01-01"),
  updatedAt: new Date("2026-01-10"),
};

export const mockItemTypes = [
  {
    id: "type-snippet",
    name: "snippet",
    label: "Snippets",
    icon: "Code",
    color: "#3b82f6",
    isSystem: true,
    route: "/items/snippets",
  },
  {
    id: "type-prompt",
    name: "prompt",
    label: "Prompts",
    icon: "Sparkles",
    color: "#8b5cf6",
    isSystem: true,
    route: "/items/prompts",
  },
  {
    id: "type-command",
    name: "command",
    label: "Commands",
    icon: "Terminal",
    color: "#f97316",
    isSystem: true,
    route: "/items/commands",
  },
  {
    id: "type-note",
    name: "note",
    label: "Notes",
    icon: "StickyNote",
    color: "#fde047",
    isSystem: true,
    route: "/items/notes",
  },
  {
    id: "type-file",
    name: "file",
    label: "Files",
    icon: "File",
    color: "#6b7280",
    isSystem: true,
    route: "/items/files",
  },
  {
    id: "type-image",
    name: "image",
    label: "Images",
    icon: "Image",
    color: "#ec4899",
    isSystem: true,
    route: "/items/images",
  },
  {
    id: "type-link",
    name: "link",
    label: "Links",
    icon: "Link",
    color: "#10b981",
    isSystem: true,
    route: "/items/links",
  },
];

export const mockItemTypeCounts = {
  all: 86,
  snippet: 24,
  prompt: 12,
  command: 8,
  note: 15,
  file: 5,
  image: 3,
  link: 19,
};

export const mockCollections = [
  {
    id: "col-react-patterns",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    itemCount: 12,
    createdAt: "2026-02-01T10:00:00.000Z",
    updatedAt: "2026-05-20T11:00:00.000Z",
  },
  {
    id: "col-python-snippets",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    itemCount: 8,
    createdAt: "2026-02-10T09:30:00.000Z",
    updatedAt: "2026-05-18T15:00:00.000Z",
  },
  {
    id: "col-context-files",
    name: "Context Files",
    description: "AI context and system prompts",
    isFavorite: true,
    itemCount: 5,
    createdAt: "2026-02-15T14:00:00.000Z",
    updatedAt: "2026-05-19T16:45:00.000Z",
  },
  {
    id: "col-interview-prep",
    name: "Interview Prep",
    description: "Technical interview resources",
    isFavorite: false,
    itemCount: 15,
    createdAt: "2026-03-01T08:00:00.000Z",
    updatedAt: "2026-05-15T17:00:00.000Z",
  },
  {
    id: "col-api-examples",
    name: "API Examples",
    description: "REST and GraphQL examples",
    isFavorite: false,
    itemCount: 9,
    createdAt: "2026-03-10T11:00:00.000Z",
    updatedAt: "2026-05-16T13:45:00.000Z",
  },
  {
    id: "col-devops-commands",
    name: "DevOps Commands",
    description: "Docker, K8s, and CI/CD commands",
    isFavorite: false,
    itemCount: 11,
    createdAt: "2026-03-20T12:00:00.000Z",
    updatedAt: "2026-05-14T16:20:00.000Z",
  },
];

export const mockItems = [
  {
    id: "item-1",
    title: "useAuth Hook",
    description: "Custom authentication hook for Next.js with NextAuth",
    type: "snippet",
    contentType: "TEXT",
    content: "import { useSession } from 'next-auth/react'",
    url: null,
    fileName: null,
    fileSize: null,
    language: "TypeScript",
    tags: ["react", "auth", "nextjs"],
    isFavorite: true,
    isPinned: true,
    collectionIds: ["col-react-patterns"],
    createdAt: "2026-05-18T09:00:00.000Z",
    updatedAt: "2026-05-21T11:00:00.000Z",
  },
  {
    id: "item-2",
    title: "useFetch Custom Hook",
    description: "SWR-based data fetching hook with TypeScript",
    type: "snippet",
    contentType: "TEXT",
    content: "import useSWR from 'swr'",
    url: null,
    fileName: null,
    fileSize: null,
    language: "TypeScript",
    tags: ["react", "swr", "fetch"],
    isFavorite: false,
    isPinned: true,
    collectionIds: ["col-react-patterns"],
    createdAt: "2026-05-17T14:30:00.000Z",
    updatedAt: "2026-05-21T08:00:00.000Z",
  },
  {
    id: "item-3",
    title: "Code Review Prompt",
    description: "Thorough prompt for reviewing pull requests",
    type: "prompt",
    contentType: "TEXT",
    content:
      "Review the following code for bugs, security issues, and style. Be concise and direct.",
    url: null,
    fileName: null,
    fileSize: null,
    language: null,
    tags: ["review", "ai", "workflow"],
    isFavorite: true,
    isPinned: false,
    collectionIds: ["col-context-files"],
    createdAt: "2026-05-16T10:15:00.000Z",
    updatedAt: "2026-05-20T16:45:00.000Z",
  },
  {
    id: "item-4",
    title: "git reset --hard HEAD~1",
    description: "Undo the last commit and discard changes",
    type: "command",
    contentType: "TEXT",
    content: "git reset --hard HEAD~1",
    url: null,
    fileName: null,
    fileSize: null,
    language: "bash",
    tags: ["git", "vcs"],
    isFavorite: false,
    isPinned: false,
    collectionIds: [],
    createdAt: "2026-05-15T08:00:00.000Z",
    updatedAt: "2026-05-20T12:30:00.000Z",
  },
  {
    id: "item-5",
    title: "Debounce Utility",
    description: "Generic debounce function for input handlers",
    type: "snippet",
    contentType: "TEXT",
    content:
      "export function debounce<T extends (...args: never[]) => void>(fn: T, ms: number) {}",
    url: null,
    fileName: null,
    fileSize: null,
    language: "TypeScript",
    tags: ["utils", "performance"],
    isFavorite: false,
    isPinned: false,
    collectionIds: ["col-react-patterns"],
    createdAt: "2026-05-14T13:00:00.000Z",
    updatedAt: "2026-05-20T09:20:00.000Z",
  },
  {
    id: "item-6",
    title: "List Comprehension Cheatsheet",
    description: "Common Python list comprehension patterns",
    type: "note",
    contentType: "TEXT",
    content: "# Python List Comprehensions\n\nsquares = [x**2 for x in range(10)]",
    url: null,
    fileName: null,
    fileSize: null,
    language: null,
    tags: ["python", "cheatsheet"],
    isFavorite: false,
    isPinned: false,
    collectionIds: ["col-python-snippets", "col-interview-prep"],
    createdAt: "2026-05-13T11:00:00.000Z",
    updatedAt: "2026-05-19T15:00:00.000Z",
  },
  {
    id: "item-7",
    title: "Docker Compose Up",
    description: "Start all services in detached mode",
    type: "command",
    contentType: "TEXT",
    content: "docker compose up -d --build",
    url: null,
    fileName: null,
    fileSize: null,
    language: "bash",
    tags: ["docker", "devops"],
    isFavorite: false,
    isPinned: false,
    collectionIds: ["col-devops-commands"],
    createdAt: "2026-05-12T09:30:00.000Z",
    updatedAt: "2026-05-19T10:10:00.000Z",
  },
  {
    id: "item-8",
    title: "System Prompt — Senior Engineer",
    description: "Context file framing the AI as a senior engineer",
    type: "file",
    contentType: "FILE",
    content: null,
    url: null,
    fileName: "senior-engineer-context.md",
    fileSize: 4096,
    language: null,
    tags: ["ai", "context"],
    isFavorite: false,
    isPinned: false,
    collectionIds: ["col-context-files"],
    createdAt: "2026-05-11T16:00:00.000Z",
    updatedAt: "2026-05-18T14:00:00.000Z",
  },
  {
    id: "item-9",
    title: "Architecture Diagram",
    description: "High-level system architecture sketch",
    type: "image",
    contentType: "FILE",
    content: null,
    url: null,
    fileName: "architecture.png",
    fileSize: 248320,
    language: null,
    tags: ["design", "architecture"],
    isFavorite: false,
    isPinned: false,
    collectionIds: [],
    createdAt: "2026-05-10T12:00:00.000Z",
    updatedAt: "2026-05-18T09:00:00.000Z",
  },
  {
    id: "item-10",
    title: "Next.js Documentation",
    description: "Official Next.js docs reference",
    type: "link",
    contentType: "URL",
    content: null,
    url: "https://nextjs.org/docs",
    fileName: null,
    fileSize: null,
    language: null,
    tags: ["nextjs", "docs"],
    isFavorite: true,
    isPinned: false,
    collectionIds: [],
    createdAt: "2026-05-09T10:00:00.000Z",
    updatedAt: "2026-05-17T11:30:00.000Z",
  },
  {
    id: "item-11",
    title: "REST Pagination Example",
    description: "Cursor-based pagination response shape",
    type: "snippet",
    contentType: "TEXT",
    content: '{ "data": [], "nextCursor": "abc123" }',
    url: null,
    fileName: null,
    fileSize: null,
    language: "json",
    tags: ["api", "rest", "pagination"],
    isFavorite: false,
    isPinned: false,
    collectionIds: ["col-api-examples"],
    createdAt: "2026-05-08T15:00:00.000Z",
    updatedAt: "2026-05-16T13:45:00.000Z",
  },
  {
    id: "item-12",
    title: "Big-O Complexity Notes",
    description: "Time and space complexity quick reference",
    type: "note",
    contentType: "TEXT",
    content: "# Big-O\n\n- O(1) constant\n- O(log n) logarithmic\n- O(n) linear",
    url: null,
    fileName: null,
    fileSize: null,
    language: null,
    tags: ["algorithms", "interview"],
    isFavorite: false,
    isPinned: false,
    collectionIds: ["col-interview-prep"],
    createdAt: "2026-05-07T09:00:00.000Z",
    updatedAt: "2026-05-15T17:00:00.000Z",
  },
  {
    id: "item-13",
    title: "Prompt Optimizer Template",
    description: "Template for rewriting vague prompts into clear ones",
    type: "prompt",
    contentType: "TEXT",
    content:
      "Rewrite the following prompt to be specific, structured, and unambiguous.",
    url: null,
    fileName: null,
    fileSize: null,
    language: null,
    tags: ["ai", "prompt"],
    isFavorite: false,
    isPinned: false,
    collectionIds: ["col-context-files"],
    createdAt: "2026-05-06T14:00:00.000Z",
    updatedAt: "2026-05-15T10:00:00.000Z",
  },
  {
    id: "item-14",
    title: "kubectl Get Pods",
    description: "List all pods across namespaces",
    type: "command",
    contentType: "TEXT",
    content: "kubectl get pods --all-namespaces",
    url: null,
    fileName: null,
    fileSize: null,
    language: "bash",
    tags: ["kubernetes", "devops"],
    isFavorite: false,
    isPinned: false,
    collectionIds: ["col-devops-commands"],
    createdAt: "2026-05-05T08:30:00.000Z",
    updatedAt: "2026-05-14T16:20:00.000Z",
  },
  {
    id: "item-15",
    title: "Tailwind CSS v4 Docs",
    description: "CSS-first configuration reference",
    type: "link",
    contentType: "URL",
    content: null,
    url: "https://tailwindcss.com/docs",
    fileName: null,
    fileSize: null,
    language: null,
    tags: ["tailwind", "css", "docs"],
    isFavorite: false,
    isPinned: false,
    collectionIds: [],
    createdAt: "2026-05-04T11:00:00.000Z",
    updatedAt: "2026-05-13T12:00:00.000Z",
  },
  {
    id: "item-16",
    title: "GraphQL Query Example",
    description: "Sample query with nested fields and variables",
    type: "snippet",
    contentType: "TEXT",
    content: "query GetUser($id: ID!) { user(id: $id) { name email } }",
    url: null,
    fileName: null,
    fileSize: null,
    language: "graphql",
    tags: ["api", "graphql"],
    isFavorite: false,
    isPinned: false,
    collectionIds: ["col-api-examples"],
    createdAt: "2026-05-03T13:00:00.000Z",
    updatedAt: "2026-05-12T14:30:00.000Z",
  },
];