import {
	File,
	FileArchive,
	FileAudio,
	FileCode,
	FileImage,
	FileJson,
	FileSpreadsheet,
	FileText,
	FileVideo,
	type LucideIcon,
} from "lucide-react";

const EXT_ICONS: Record<string, LucideIcon> = {
	pdf: FileText,
	doc: FileText,
	docx: FileText,
	txt: FileText,
	md: FileText,
	rtf: FileText,
	xls: FileSpreadsheet,
	xlsx: FileSpreadsheet,
	csv: FileSpreadsheet,
	tsv: FileSpreadsheet,
	zip: FileArchive,
	rar: FileArchive,
	tar: FileArchive,
	gz: FileArchive,
	"7z": FileArchive,
	json: FileJson,
	jpg: FileImage,
	jpeg: FileImage,
	png: FileImage,
	gif: FileImage,
	webp: FileImage,
	svg: FileImage,
	mp4: FileVideo,
	mov: FileVideo,
	avi: FileVideo,
	mkv: FileVideo,
	webm: FileVideo,
	mp3: FileAudio,
	wav: FileAudio,
	ogg: FileAudio,
	flac: FileAudio,
	js: FileCode,
	jsx: FileCode,
	ts: FileCode,
	tsx: FileCode,
	py: FileCode,
	rb: FileCode,
	go: FileCode,
	rs: FileCode,
	java: FileCode,
	c: FileCode,
	cpp: FileCode,
	h: FileCode,
	css: FileCode,
	scss: FileCode,
	html: FileCode,
	sh: FileCode,
	yml: FileCode,
	yaml: FileCode,
	toml: FileCode,
	xml: FileCode,
};

export function iconForFileName(fileName: string | null): LucideIcon {
	if (!fileName) return File;
	const ext = fileName.split(".").pop()?.toLowerCase() ?? "";
	return EXT_ICONS[ext] ?? File;
}
